const Data = [
  {
    id: "1",
    title: "Palm Harbor",
    category: "Apartment",
    price: 1500,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/Luxury-house-exterior.jpg",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "2",
    title: "Beverly Springfield ",
    category: "Apartment",
    price: 2200,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/Luxury-house-and-garden.jpg",
    desc: " A quintessential South Indian Apartment! Made with protein-packed urad dal and semolina followed by crunchy veggies and curd, this recipe makes for a hearty morning meal. With some grated coconut on top, it gives a beautiful south-Indian flavour.",
  },
  {
    id: "3",
    title: "Faulker Ave",
    category: "Apartment",
    price: 3000,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/Cliff-side-house.jpg",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
  },
  {
    id: "4",
    title: "Mamta Niwas",
    category: "Villa",
    price: 1600,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/modern-house-exterior.jpg",
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder and some mango powder, which is what gives the chana it's sour and tangy taste.",
  },
  {
    id: "5",
    title: "Jagat Niwas",
    category: "Villa",
    price: 2800,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/luxury-beach-house.jpg",
    desc: "Eggs are a versatile food that can be cooked for any meal of the day. From Apartment to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt and fresh coriander.",
  },
  {
    id: "6",
    title: "Avenue Street",
    category: "Villa",
    price: 1950,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/unique-house-design.jpg",
    desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
  },
  {
    id: "7",
    title: "Mall Road",
    category: "2-BHK",
    price: 2130,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/unique-house-design.jpg",
    desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
  },
  {
    id: "8",
    title: "Baker street",
    category: "2-BHK",
    price: 3200,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/modern-home-design-ideas.jpg",
    desc: "Your family will thank you for this absolutely fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions and some ghee.",
  },
  {
    id: "9",
    title: "Park Road",
    category: "2-BHK",
    price: 2700,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/luxury-house-with-glass-pool.jpg",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "10",
    title: "Lasota Complex",
    category: "2-BHK",
    price: 1600,
    img: "http://cdn.home-designing.com/wp-content/uploads/2020/04/luxury-house-architecture.jpg",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
];

export default Data;
